environment:
  global:
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    WITH_COMPILER: "cmd /E:ON /V:ON /C C:\\project\\.ci\\appveyor\\run_with_compiler.cmd"

  matrix:
    - PYTHON: "C:\\Python26"
      PYTHON_VERSION: "2.6.x"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python26-x64"
      PYTHON_VERSION: "2.6.x"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python33"
      PYTHON_VERSION: "3.3.x"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python33-x64"
      PYTHON_VERSION: "3.3.x"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python34"
      PYTHON_VERSION: "3.4.x"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python34-x64"
      PYTHON_VERSION: "3.4.x"
      PYTHON_ARCH: "64"

build: false  # Not a C# project, build stuff at the test step instead.
clone_folder: c:\\project

install:
  - ps: cd C:\\project

  # Install some additional Python modules which will be required by
  # the tests.  These can't be installed as part of the setup.py due
  # to file locking issues.
  - "%PYTHON%\\Scripts\\pip.exe install virtualenv"
  - "%PYTHON%\\Scripts\\virtualenv.exe C:\\virtualenv\\precompiled"
  - "%PYTHON%\\Scripts\\virtualenv.exe C:\\virtualenv\\inline"
  - "%WITH_COMPILER% C:\\virtualenv\\precompiled\\Scripts\\pip.exe install -r dev-requirements.txt"
  - "%WITH_COMPILER% C:\\virtualenv\\inline\\Scripts\\pip.exe install -r dev-requirements.txt"

test_script:
  # Precompiled test
  - ps: cd C:\\project
  - "copy /Y .ci\\appveyor\\precompiled.ini %HOMEDRIVE%%HOMEPATH%\\pywincffi.ini"
  - "%WITH_COMPILER% C:\\virtualenv\\precompiled\\Scripts\\python.exe bdist_wheel"
  - "%WITH_COMPILER% C:\\virtualenv\\precompiled\\Scripts\\python.exe setup.py install"
  - ps: C:\\
  - "C:\\virtualenv\\precompiled\\Scripts\\nosetests.exe --with-coverage --cover-package pywincffi -v C:\\project\\tests"

  # Inline test
  - "copy /Y C:\\project\\.ci\\appveyor\\inline.ini %HOMEDRIVE%%HOMEPATH%\\pywincffi.ini"
  - "%WITH_COMPILER% C:\\virtualenv\\inline\\Scripts\\python.exe setup.py develop"
  - ps: C:\\
  - "C:\\virtualenv\\inline\\Scripts\\nosetests.exe --with-coverage --cover-package pywincffi -v C:\\project\\tests"


artifacts:
  - path: dist\*.whl
